export default {
  index: 'Front 로드맵',
  'front-architecture': '프론트엔드 역사와 미래',
  'eslint-prettier': 'ESLint & Prettier',
  '-- (1) CSR --': {
    type: 'separator',
    title: '(1) CSR',
  },
  react: 'React',
  svelte: 'Svelte',
  '-- (2) 렌더링 프레임워크 --': {
    type: 'separator',
    title: '(2) 렌더링 프레임워크',
  },
  nextjs: 'NextJs',
  '-- (3) Data Fetching --': {
    type: 'separator',
    title: '(3) Data Fetching',
  },
  'data-fetching': 'Data Fetching 라이브러리',
  'apollo-client': 'Apollo Client',
  'tanstack-query': 'Tanstack Query',
  '-- (4) Router 라이브러리 --': {
    type: 'separator',
    title: '(4) Router 라이브러리',
  },
  'react-router': 'React-Router',
  '-- (5) State Management --': {
    type: 'separator',
    title: '(5) State Management',
  },
  'state-management': '상태 관리 라이브러리',
  'redux-toolkit': 'Redux ToolKit',
  recoil: 'Recoil',
  mobx: 'Mobx',
  zustand: 'Zustand',
  '-- (6) Styling 라이브러리 --': {
    type: 'separator',
    title: '(6) Styling 라이브러리',
  },
  styling: 'Styling 라이브러리',
  postcss: 'PostCSS',
  sass: 'Sass',
  emotion: 'Emotion',
  'styled-components': 'Styled Components',
  tailwindcss: 'TailwindCSS',
  '-- (7) UI 라이브러리 --': {
    type: 'separator',
    title: '(7) UI 라이브러리',
  },
  'ui-lib-kind': 'UI 라이브러리 종류',
  'ui-lib': 'UI 라이브러리',
  '-- (8) Test 라이브러리 --': {
    type: 'separator',
    title: '(8) Test 라이브러리',
  },
  'front-test': '프론트엔드 테스트',
  jest: 'Jest',
  cypress: 'Cypress',
  'react-test-lib': 'React Test Lib(RTL)',
  storybook: 'Storybook',
  '-- (9) 배포 --': {
    type: 'separator',
    title: '(9) 배포',
  },
  deploy: '배포',
  '-- (10) 3D & 인터랙티브 --': {
    type: 'separator',
    title: '(10) 3D & 인터랙티브',
  },
  '-- (11) 기타 --': {
    type: 'separator',
    title: '(11) 기타',
  },
}
