export default {
  '00-csr-ssr-ssg': '00-CSR, SSR, SSG 역사',
  '00-summary': '00-Next.js 요약',
  '00-others': '00-Next.js 기타 기능',
  '-- 공식문서 --': {
    type: 'separator',
    title: '공식문서',
  },
  started: '01-설치',
  'project-structure': '02-프로젝트 구조',
  '-- 공식문서 응용 프로그램 빌드 --': {
    type: 'separator',
    title: '응용 프로그램 빌드',
  },
  '01-routing': 'Routing',
  '02-data-fetching': 'Data Fetching',
  '03-rendering': 'Rendering',
  '04-caching': 'Caching',
  '05-styling': 'Styling',
  '06-optimizing': 'Optimizing',
  '07-configuring': 'Configuring',
  '08-testing': 'Testing',
  '09-authentication': 'Authentication',
  '10-deploying': 'Deploying',
  '11-API-Ref': 'API-Ref',
}
